controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller_velocity:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller_velocity:
  ros__parameters:
    joints:
      - ax1_joint
      - ax2_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
