controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

#hardcode joints namespaces for now
forward_velocity_controller:
  ros__parameters:
    joints:
      - ax1_joint
      - ax2_joint
    interface_name: velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - ax1_joint
      - ax2_joint
    interface_name: velocity
    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity
    gains:
      ax1_joint:
        ff_velocity_scale: 1.0  # Adjust this as needed
      ax2_joint:
        ff_velocity_scale: 1.0 