controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: drone1/joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: drone1/forward_command_controller/ForwardCommandController    

    joint_state_broadcaster:
      type: drone1/joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - ax1_joint
      - ax2_joint
    interface_name: position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - ax1_joint
      - ax2_joint
    interface_name: position
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
